apiVersion: v2
name: hms-stack
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://frontend"
  - name: backend
    version: 0.1.0
    repository: "file://backend"
  - name: telemedicine
    version: 0.1.0
    repository: "file://telemedicine"
  - name: notification
    version: 0.1.0
    repository: "file://notification"
