apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-backend-config
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}-backend
data:
  AWS_REGION: {{ .Values.global.region }}
  S3_BUCKET: {{ .Values.global.s3.bucket }}
  DDB_TABLE: {{ .Values.global.dynamodb.table }}
  COGNITO_USER_POOL_ID: {{ .Values.global.cognito.userPoolId }}
  COGNITO_CLIENT_ID: {{ .Values.global.cognito.clientId }}
  COGNITO_JWKS_URL: {{ .Values.global.cognito.jwksUrl }}
  POSTGRES_HOST: {{ .Values.global.postgres.host }}
  POSTGRES_DB: {{ .Values.global.postgres.db }}
  POSTGRES_USER: {{ .Values.global.postgres.user }}
