apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-backend
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.global.appName }}-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
