apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.global.appName }}-backend
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.global.appName }}-backend
  updatePolicy:
    updateMode: "Auto"
