apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemedicine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "telemedicine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "telemedicine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
