apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.global.appName }}-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.global.appName }}-frontend
