apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-frontend
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.global.appName }}-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
