apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "frontend.fullname" . }}
  updatePolicy:
    updateMode: Auto
